# Generated by Django 4.1.3 on 2022-12-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0002_coment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='coment',
        ),
        migrations.AddField(
            model_name='coment',
            name='comment',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
