# Generated by Django 4.1.3 on 2022-12-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0004_company_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
